In [1]:
import numpy as np

In [12]:
a = np.array([1,2,3], dtype = "int64")
a

array([1, 2, 3])

In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
b.ndim

2

In [6]:
b.dtype

dtype('float64')

In [7]:
b.shape

(2, 3)

In [13]:
a.itemsize

8