In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
a +2

array([3, 4, 5])

In [6]:
a-2

array([-1,  0,  1])

In [9]:
a*2

array([2, 4, 6])

In [10]:
a/2

array([0.5, 1. , 1.5])

In [13]:
b = np.array([1,2,3])
a+b

array([2, 4, 6])

In [14]:
# take the trigonometry functions of the values 
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

##### linear algebra

In [19]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [26]:
# find the determinant 
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Statistics

In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.min(stats)

np.int64(1)

In [30]:
np.max(stats,axis = 1)

array([3, 6])

In [33]:
np.sum(stats , axis = 1)

array([ 6, 15])

In [5]:
import numpy as np
# load data from file into numpy array
# np.genfromtxt('data.txt',delimiter  = ',')