In [2]:
import numpy as np

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
# get a element (row,column)
a[1,5]

np.int64(13)

In [4]:
# get an specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
#get an specific column
a[:,2]

array([ 3, 10])

In [10]:
#getting element i  [start,end,size]
a[0,1:6:2]

array([2, 4, 6])

In [11]:
a[1,5] = 30
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 30 14]]


In [15]:
b = np.array([[[1,2],[8,3]],[[4,5],[6,7]]])
print(b)


[[[1 2]
  [8 3]]

 [[4 5]
  [6 7]]]


In [17]:
b[0,1,1]

np.int64(3)

# TYPES OF MATRIX

In [6]:
# all zero's matrix
import numpy as np
np.zeros((3,2,5,1))

array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.]]]])

In [11]:
# all 1's matrix
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [14]:
# any numbers matrix
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [19]:
# random decimal numbers matrix
np.random.rand(4,2)
# random shape giving
np.random.random_sample(4)

array([0.03745543, 0.92903214, 0.94972465, 0.69511233])

In [24]:
# random integer numbers
np.random.randint(2,6, size = (3,3))

array([[3, 3, 2],
       [3, 3, 2],
       [5, 4, 5]], dtype=int32)

In [27]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
output = np.ones([5,5])

z = np.zeros([3,3])

z[1,1] = 9 

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# be careful while copying arrays!!!

In [52]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 100
print(a)

[1 2 3]
